/* Generated by the Nim Compiler v1.7.3 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI503316494 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI503316488 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI503316499 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI33555835 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555171 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555179 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555178 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555175 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555176 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217763 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NNI134217763 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217763.node = NNI134217763;
var NNI33555176 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555176.node = NNI33555176;
NTI33555178.base = NTI33555175;
NTI33555179.base = NTI33555175;
var NNI33555175 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555178, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555179, name: "up", sons: null}]};
NTI33555175.node = NNI33555175;
var NNI33555171 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555171.node = NNI33555171;
NTI33555175.base = NTI33555171;
NTI33555176.base = NTI33555175;
NTI134217763.base = NTI33555176;
var NNI33555835 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554450, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}, 
{kind: 1, offset: "Field2", len: 0, typ: NTI33554450, name: "Field2", sons: null}]};
NTI33555835.node = NNI33555835;
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
NTI134217741.base = NTI33555176;
NTI134217743.base = NTI134217741;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555176;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555176;
var NNI503316499 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI503316499.node = NNI503316499;
var NNI503316488 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "nombre", len: 0, typ: NTI33554449, name: "nombre", sons: null}, 
{kind: 1, offset: "edad", len: 0, typ: NTI33554435, name: "edad", sons: null}]};
NTI503316488.node = NNI503316488;
NTI503316488.base = NTI33555171;
NTI503316499.base = NTI503316488;
var NNI503316494 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI503316494.node = NNI503316494;
NTI503316494.base = NTI503316488;

function toJSStr(s_33556759) {
  var result_33556760 = null;

    var res_33556794 = newSeq_33556777((s_33556759).length);
    var i_33556795 = 0;
    var j_33556796 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556795 < (s_33556759).length)) break Label2;
          var c_33556797 = s_33556759[i_33556795];
          if ((c_33556797 < 128)) {
          res_33556794[j_33556796] = String.fromCharCode(c_33556797);
          i_33556795 += 1;
          }
          else {
            var helper_33556809 = newSeq_33556777(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556810 = c_33556797.toString(16);
                  if ((((code_33556810) == null ? 0 : (code_33556810).length) == 1)) {
                  helper_33556809.push("%0");;
                  }
                  else {
                  helper_33556809.push("%");;
                  }
                  
                  helper_33556809.push(code_33556810);;
                  i_33556795 += 1;
                  if ((((s_33556759).length <= i_33556795) || (s_33556759[i_33556795] < 128))) {
                  break Label3;
                  }
                  
                  c_33556797 = s_33556759[i_33556795];
                }
            };
++excHandler;
            try {
            res_33556794[j_33556796] = decodeURIComponent(helper_33556809.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556794[j_33556796] = helper_33556809.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556796 += 1;
        }
    };
    if (res_33556794.length < j_33556796) { for (var i = res_33556794.length ; i < j_33556796 ; ++i) res_33556794.push(null); }
               else { res_33556794.length = j_33556796; };
    result_33556760 = res_33556794.join("");

  return result_33556760;

}

function rawEcho() {
          var buf = "";
      for (var i = 0; i < arguments.length; ++i) {
        buf += toJSStr(arguments[i]);
      }
      console.log(buf);
    

  
}

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_33557092, src_33557093, ti_33557094) {
  var result_33557103 = null;

    switch (ti_33557094.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer_33557083(ti_33557094))) {
      result_33557103 = src_33557093;
      }
      else {
        result_33557103 = [src_33557093[0], src_33557093[1]];
      }
      
      break;
    case 19:
            if (dest_33557092 === null || dest_33557092 === undefined) {
        dest_33557092 = {};
      }
      else {
        for (var key in dest_33557092) { delete dest_33557092[key]; }
      }
      for (var key in src_33557093) { dest_33557092[key] = src_33557093[key]; }
      result_33557103 = dest_33557092;
    
      break;
    case 18:
    case 17:
      if (!((ti_33557094.base == null))) {
      result_33557103 = nimCopy(dest_33557092, src_33557093, ti_33557094.base);
      }
      else {
      if ((ti_33557094.kind == 17)) {
      result_33557103 = (dest_33557092 === null || dest_33557092 === undefined) ? {m_type: ti_33557094} : dest_33557092;
      }
      else {
        result_33557103 = (dest_33557092 === null || dest_33557092 === undefined) ? {} : dest_33557092;
      }
      }
      nimCopyAux(result_33557103, src_33557093, ti_33557094.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_33557093)) { 
        if(dest_33557092 === null || dest_33557092 === undefined || dest_33557092.length != src_33557093.length) {
          dest_33557092 = new src_33557093.constructor(src_33557093);
        } else {
          dest_33557092.set(src_33557093, 0);
        }
        result_33557103 = dest_33557092;
      } else {
        if (src_33557093 === null) {
          result_33557103 = null;
        }
        else {
          if (dest_33557092 === null || dest_33557092 === undefined || dest_33557092.length != src_33557093.length) {
            dest_33557092 = new Array(src_33557093.length);
          }
          result_33557103 = dest_33557092;
          for (var i = 0; i < src_33557093.length; ++i) {
            result_33557103[i] = nimCopy(result_33557103[i], src_33557093[i], ti_33557094.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_33557093 === null) {
        result_33557103 = null;
      }
      else {
        if (dest_33557092 === null || dest_33557092 === undefined || dest_33557092.length != src_33557093.length) {
          dest_33557092 = new Array(src_33557093.length);
        }
        result_33557103 = dest_33557092;
        for (var i = 0; i < src_33557093.length; ++i) {
          result_33557103[i] = nimCopy(result_33557103[i], src_33557093[i], ti_33557094.base);
        }
      }
    
      break;
    case 28:
            if (src_33557093 !== null) {
        result_33557103 = src_33557093.slice(0);
      }
    
      break;
    default: 
      result_33557103 = src_33557093;
      break;
    }

  return result_33557103;

}

function arrayConstr(len_33557131, value_33557132, typ_33557133) {
        var result = new Array(len_33557131);
    for (var i = 0; i < len_33557131; ++i) result[i] = nimCopy(null, value_33557132, typ_33557133);
    return result;
  

  
}

function mnewString(len_33556845) {
        return new Array(len_33556845);
  

  
}

function addInt(a_33556892, b_33556893) {
        var result = a_33556892 + b_33556893;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_33557141, a_33557142, b_33557143) {
  var result_33557144 = 0;

  BeforeRet: {
    if (((a_33557142 <= i_33557141) && (i_33557141 <= b_33557143))) {
    result_33557144 = i_33557141;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557144;

}

function chckIndx(i_33557136, a_33557137, b_33557138) {
  var result_33557139 = 0;

  BeforeRet: {
    if (((a_33557137 <= i_33557136) && (i_33557136 <= b_33557138))) {
    result_33557139 = i_33557136;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_33557136, a_33557137, b_33557138);
    }
    
  };

  return result_33557139;

}

function cstrToNimstr(c_33556756) {
      var ln = c_33556756.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_33556756.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_33556756.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}

function raiseException(e_33556619, ename_33556620) {
    e_33556619.name = ename_33556620;
    if ((excHandler == 0)) {
    unhandledException(e_33556619);
    }
    
    e_33556619.trace = nimCopy(null, rawWriteStackTrace_33556583(), NTI33554449);
    throw e_33556619;

  
}

function isObj(obj_33557190, subclass_33557191) {
  var result_33557192 = false;

  BeforeRet: {
    var x_33557193 = obj_33557190;
    if ((x_33557193 == subclass_33557191)) {
    result_33557192 = true;
    break BeforeRet;
    }
    
    Label1: {
        Label2: while (true) {
        if (!!((x_33557193 == subclass_33557191))) break Label2;
          if ((x_33557193 == null)) {
          result_33557192 = false;
          break BeforeRet;
          }
          
          x_33557193 = x_33557193.base;
        }
    };
    result_33557192 = true;
    break BeforeRet;
  };

  return result_33557192;

}
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module programa", prev: framePtr, filename: "/Users/marcofuentes/Documents/UVG/10mo/compiladores/nim_blog/programa.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function newSeq_33556777(len_33556779) {
  var result_33556780 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 604;
    result_33556780 = new Array(len_33556779); for (var i = 0 ; i < len_33556779 ; ++i) { result_33556780[i] = null; }  framePtr = F.prev;

  return result_33556780;

}
var F = {procname: "module programa", prev: framePtr, filename: "/Users/marcofuentes/Documents/UVG/10mo/compiladores/nim_blog/programa.nim", line: 0};
framePtr = F;
F.line = 3;
var mensaje_503316482 = [[72,111,108,97,32,109,117,110,100,111,33]];
F.line = 4;
rawEcho(mensaje_503316482[0]);
framePtr = F.prev;
var F = {procname: "module programa", prev: framePtr, filename: "/Users/marcofuentes/Documents/UVG/10mo/compiladores/nim_blog/programa.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module programa", prev: framePtr, filename: "/Users/marcofuentes/Documents/UVG/10mo/compiladores/nim_blog/programa.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module programa", prev: framePtr, filename: "/Users/marcofuentes/Documents/UVG/10mo/compiladores/nim_blog/programa.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module programa", prev: framePtr, filename: "/Users/marcofuentes/Documents/UVG/10mo/compiladores/nim_blog/programa.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module programa", prev: framePtr, filename: "/Users/marcofuentes/Documents/UVG/10mo/compiladores/nim_blog/programa.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module programa", prev: framePtr, filename: "/Users/marcofuentes/Documents/UVG/10mo/compiladores/nim_blog/programa.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module programa", prev: framePtr, filename: "/Users/marcofuentes/Documents/UVG/10mo/compiladores/nim_blog/programa.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module programa", prev: framePtr, filename: "/Users/marcofuentes/Documents/UVG/10mo/compiladores/nim_blog/programa.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module programa", prev: framePtr, filename: "/Users/marcofuentes/Documents/UVG/10mo/compiladores/nim_blog/programa.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function isFatPointer_33557083(ti_33557084) {
  var result_33557085 = false;

  BeforeRet: {
    result_33557085 = !((ConstSet1[ti_33557084.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557085;

}

function nimCopyAux(dest_33557096, src_33557097, n_33557098) {
    switch (n_33557098.kind) {
    case 0:
      break;
    case 1:
            dest_33557096[n_33557098.offset] = nimCopy(dest_33557096[n_33557098.offset], src_33557097[n_33557098.offset], n_33557098.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_33557098.sons.length; i++) {
      nimCopyAux(dest_33557096, src_33557097, n_33557098.sons[i]);
    }
    
      break;
    case 3:
            dest_33557096[n_33557098.offset] = nimCopy(dest_33557096[n_33557098.offset], src_33557097[n_33557098.offset], n_33557098.typ);
      for (var i = 0; i < n_33557098.sons.length; ++i) {
        nimCopyAux(dest_33557096, src_33557097, n_33557098.sons[i][1]);
      }
    
      break;
    }

  
}

function add_33556410(x_33556411, x_33556411_Idx, y_33556412) {
          if (x_33556411[x_33556411_Idx] === null) { x_33556411[x_33556411_Idx] = []; }
      var off = x_33556411[x_33556411_Idx].length;
      x_33556411[x_33556411_Idx].length += y_33556412.length;
      for (var i = 0; i < y_33556412.length; ++i) {
        x_33556411[x_33556411_Idx][off+i] = y_33556412.charCodeAt(i);
      }
    

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_33556890) {
        if (a_33556890 > 2147483647 || a_33556890 < -2147483648) raiseOverflow();
  

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function raiseIndexError(i_33556706, a_33556707, b_33556708) {
    var Temporary1;

    if ((b_33556708 < a_33556707)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32] || []).concat(HEX24_352321544(i_33556706) || [],[32,110,111,116,32,105,110,32] || [],HEX24_352321544(a_33556707) || [],[32,46,46,32] || [],HEX24_352321544(b_33556708) || []);
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function addChars_285212847(result_285212849, result_285212849_Idx, x_285212850, start_285212851, n_285212852) {
  var F = {procname: "addChars.addChars", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 43;
    var old_285212853 = (result_285212849[result_285212849_Idx]).length;
    F.line = 44;
    (result_285212849[result_285212849_Idx].length = chckRange(addInt(old_285212853, n_285212852), 0, 2147483647));
    Label1: {
      F.line = 46;
      var iHEX60gensym4_285212867 = 0;
      F.line = 119;
      var i_503316559 = 0;
      Label2: {
        F.line = 120;
          Label3: while (true) {
          if (!(i_503316559 < n_285212852)) break Label3;
            F.line = 49;
            iHEX60gensym4_285212867 = i_503316559;
            F.line = 49;
            result_285212849[result_285212849_Idx][chckIndx(addInt(old_285212853, iHEX60gensym4_285212867), 0, (result_285212849[result_285212849_Idx]).length - 1)] = x_285212850.charCodeAt(chckIndx(addInt(start_285212851, iHEX60gensym4_285212867), 0, (x_285212850).length - 1));
            F.line = 122;
            i_503316559 = addInt(i_503316559, 1);
          }
      };
    };
  framePtr = F.prev;

  
}

function addChars_285212843(result_285212845, result_285212845_Idx, x_285212846) {
  var F = {procname: "addChars.addChars", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 55;
    addChars_285212847(result_285212845, result_285212845_Idx, x_285212846, 0, ((x_285212846) == null ? 0 : (x_285212846).length));
  framePtr = F.prev;

  
}

function addInt_285212868(result_285212869, result_285212869_Idx, x_285212870) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 113;
    addChars_285212843(result_285212869, result_285212869_Idx, ((x_285212870) + ""));
  framePtr = F.prev;

  
}

function addInt_285212889(result_285212890, result_285212890_Idx, x_285212891) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 117;
    addInt_285212868(result_285212890, result_285212890_Idx, x_285212891);
  framePtr = F.prev;

  
}

function HEX24_352321544(x_352321545) {
  var result_352321546 = [[]];

  var F = {procname: "dollars.$", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/system/dollars.nim", line: 0};
  framePtr = F;
    F.line = 18;
    addInt_285212889(result_352321546, 0, x_352321545);
  framePtr = F.prev;

  return result_352321546[0];

}

function auxWriteStackTrace_33556511(f_33556512) {
  var result_33556513 = [[]];

    var it_33556521 = f_33556512;
    var i_33556522 = 0;
    var total_33556523 = 0;
    var tempFrames_33556524 = arrayConstr(64, {Field0: null, Field1: 0, Field2: null}, NTI33555835);
    Label1: {
        Label2: while (true) {
        if (!(!((it_33556521 == null)) && (i_33556522 <= 63))) break Label2;
          tempFrames_33556524[i_33556522].Field0 = it_33556521.procname;
          tempFrames_33556524[i_33556522].Field1 = it_33556521.line;
          tempFrames_33556524[i_33556522].Field2 = it_33556521.filename;
          i_33556522 += 1;
          total_33556523 += 1;
          it_33556521 = it_33556521.prev;
        }
    };
    Label3: {
        Label4: while (true) {
        if (!!((it_33556521 == null))) break Label4;
          total_33556523 += 1;
          it_33556521 = it_33556521.prev;
        }
    };
    result_33556513[0] = nimCopy(null, [], NTI33554449);
    if (!((total_33556523 == i_33556522))) {
    result_33556513[0].push.apply(result_33556513[0], [40]);;
    result_33556513[0].push.apply(result_33556513[0], HEX24_352321544((total_33556523 - i_33556522)));;
    result_33556513[0].push.apply(result_33556513[0], [32,99,97,108,108,115,32,111,109,105,116,116,101,100,41,32,46,46,46,10]);;
    }
    
    Label5: {
      var j_33556554 = 0;
      var colontmp__503316551 = 0;
      colontmp__503316551 = (i_33556522 - 1);
      var res_503316553 = colontmp__503316551;
      Label6: {
          Label7: while (true) {
          if (!(0 <= res_503316553)) break Label7;
            j_33556554 = res_503316553;
            result_33556513[0].push.apply(result_33556513[0], cstrToNimstr(tempFrames_33556524[j_33556554].Field2));;
            if ((0 < tempFrames_33556524[j_33556554].Field1)) {
            result_33556513[0].push.apply(result_33556513[0], [40]);;
            addInt_285212889(result_33556513, 0, tempFrames_33556524[j_33556554].Field1);
            if (false) {
            result_33556513[0].push.apply(result_33556513[0], [44,32]);;
            addInt_285212889(result_33556513, 0, 0);
            }
            
            result_33556513[0].push.apply(result_33556513[0], [41]);;
            }
            
            result_33556513[0].push.apply(result_33556513[0], [32,97,116,32]);;
            add_33556410(result_33556513, 0, tempFrames_33556524[j_33556554].Field0);
            result_33556513[0].push.apply(result_33556513[0], [10]);;
            res_503316553 -= 1;
          }
      };
    };

  return result_33556513[0];

}

function rawWriteStackTrace_33556583() {
  var result_33556584 = [];

    if (!((framePtr == null))) {
    result_33556584 = nimCopy(null, ([84,114,97,99,101,98,97,99,107,32,40,109,111,115,116,32,114,101,99,101,110,116,32,99,97,108,108,32,108,97,115,116,41,10] || []).concat(auxWriteStackTrace_33556511(framePtr) || []), NTI33554449);
    }
    else {
      result_33556584 = nimCopy(null, [78,111,32,115,116,97,99,107,32,116,114,97,99,101,98,97,99,107,32,97,118,97,105,108,97,98,108,101,10], NTI33554449);
    }
    

  return result_33556584;

}

function unhandledException(e_33556615) {
    var buf_33556616 = [[]];
    if (!(((e_33556615.message).length == 0))) {
    buf_33556616[0].push.apply(buf_33556616[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    buf_33556616[0].push.apply(buf_33556616[0], e_33556615.message);;
    }
    else {
    buf_33556616[0].push.apply(buf_33556616[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    buf_33556616[0].push.apply(buf_33556616[0], [32,91]);;
    add_33556410(buf_33556616, 0, e_33556615.name);
    buf_33556616[0].push.apply(buf_33556616[0], [93,10]);;
    buf_33556616[0].push.apply(buf_33556616[0], rawWriteStackTrace_33556583());;
    var cbuf_33556617 = toJSStr(buf_33556616[0]);
    framePtr = null;
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556617);
  }
  else {
    throw cbuf_33556617;
  }
  

  
}

function sysFatal_33556955(message_33556958) {
  var F = {procname: "sysFatal.sysFatal", prev: framePtr, filename: "/Users/marcofuentes/Documents/Nim/lib/system/fatal.nim", line: 0};
  framePtr = F;
    F.line = 54;
    raiseException({message: nimCopy(null, message_33556958, NTI33554449), m_type: NTI134217763, parent: null, name: null, trace: [], up: null}, "NilAccessDefect");
  framePtr = F.prev;

  
}

function chckNilDisp(p_33556954, p_33556954_Idx) {
    if ((p_33556954 == null && p_33556954_Idx == 0)) {
    sysFatal_33556955([99,97,110,110,111,116,32,100,105,115,112,97,116,99,104,59,32,100,105,115,112,97,116,99,104,101,114,32,105,115,32,110,105,108]);
    }
    

  
}

function vocalize_503316509(self_503316510) {
  var result_503316511 = [];

  var F = {procname: "programa.vocalize", prev: framePtr, filename: "/Users/marcofuentes/Documents/UVG/10mo/compiladores/nim_blog/programa.nim", line: 0};
  framePtr = F;
    F.line = 20;
    result_503316511 = nimCopy(null, [81,117,105,101,114,111,32,115,101,114,32,105,110,103,46,46,46], NTI33554449);
  framePtr = F.prev;

  return result_503316511;

}

function vocalize_503316501(self_503316502) {
  var result_503316503 = [];

  var F = {procname: "programa.vocalize", prev: framePtr, filename: "/Users/marcofuentes/Documents/UVG/10mo/compiladores/nim_blog/programa.nim", line: 0};
  framePtr = F;
    F.line = 16;
    result_503316503 = nimCopy(null, [83,111,121,32,109,101,106,111,114], NTI33554449);
  framePtr = F.prev;

  return result_503316503;

}

function vocalize_503316489(self_503316490) {
  var result_503316491 = [];

  var F = {procname: "programa.vocalize", prev: framePtr, filename: "/Users/marcofuentes/Documents/UVG/10mo/compiladores/nim_blog/programa.nim", line: 0};
  framePtr = F;
    F.line = 12;
    result_503316491 = nimCopy(null, [46,46,46], NTI33554449);
  framePtr = F.prev;

  return result_503316491;

}

function vocalize_503316492(self_503316490) {
  var result_503316493 = [];

  var F = {procname: "programa.vocalize", prev: framePtr, filename: "/Users/marcofuentes/Documents/UVG/10mo/compiladores/nim_blog/programa.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 531;
    chckNilDisp(self_503316490);
    if (isObj(self_503316490.m_type, NTI503316499)) {
    F.line = 12;
    result_503316493 = vocalize_503316509(self_503316490);
    break BeforeRet;
    }
    else {
    if (isObj(self_503316490.m_type, NTI503316494)) {
    F.line = 12;
    result_503316493 = vocalize_503316501(self_503316490);
    break BeforeRet;
    }
    else {
    if (isObj(self_503316490.m_type, NTI503316488)) {
    F.line = 12;
    result_503316493 = vocalize_503316489(self_503316490);
    break BeforeRet;
    }
    }}
  };
  framePtr = F.prev;

  return result_503316493;

}

function edadAnios_503316504(self_503316505) {
  var result_503316506 = 0;

  var F = {procname: "programa.edadAnios", prev: framePtr, filename: "/Users/marcofuentes/Documents/UVG/10mo/compiladores/nim_blog/programa.nim", line: 0};
  framePtr = F;
    F.line = 17;
    result_503316506 = addInt(self_503316505.edad, 7);
  framePtr = F.prev;

  return result_503316506;

}

function edadAnios_503316494(self_503316495) {
  var result_503316496 = 0;

  var F = {procname: "programa.edadAnios", prev: framePtr, filename: "/Users/marcofuentes/Documents/UVG/10mo/compiladores/nim_blog/programa.nim", line: 0};
  framePtr = F;
    F.line = 13;
    result_503316496 = self_503316495.edad;
  framePtr = F.prev;

  return result_503316496;

}

function edadAnios_503316497(self_503316495) {
  var result_503316498 = 0;

  var F = {procname: "programa.edadAnios", prev: framePtr, filename: "/Users/marcofuentes/Documents/UVG/10mo/compiladores/nim_blog/programa.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 531;
    chckNilDisp(self_503316495);
    if (isObj(self_503316495.m_type, NTI503316494)) {
    F.line = 13;
    result_503316498 = edadAnios_503316504(self_503316495);
    break BeforeRet;
    }
    else {
    if (isObj(self_503316495.m_type, NTI503316488)) {
    F.line = 13;
    result_503316498 = edadAnios_503316494(self_503316495);
    break BeforeRet;
    }
    }
  };
  framePtr = F.prev;

  return result_503316498;

}
